# Generated by Django 5.1.2 on 2025-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
